[package]
name = "anatoly"
version = "0.1.0"
edition = "2024"

[dependencies]
rig-core = "0.32.0"
serde = "1.0.228"
serde_json = "1.0.149"
thiserror = "2.0.18"
tokio = { version = "1.50.0", features = ["macros", "rt-multi-thread"] }
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }

[dev-dependencies]
insta = "1.46.3"
